# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
drop_dense_internal <- function(sorted_sample, sorted_theoretical, N_hard) {
    .Call('_fastqq_drop_dense_internal', PACKAGE = 'fastqq', sorted_sample, sorted_theoretical, N_hard)
}

#' @noRd
drop_dense_qq <- function(sample, N_hard) {
    .Call('_fastqq_drop_dense_qq', PACKAGE = 'fastqq', sample, N_hard)
}

#' @noRd
drop_dense_qqlog <- function(log10_pvals, N_hard) {
    .Call('_fastqq_drop_dense_qqlog', PACKAGE = 'fastqq', log10_pvals, N_hard)
}

#' @noRd
drop_dense_chisq1 <- function(chisq_vals, N_hard) {
    .Call('_fastqq_drop_dense_chisq1', PACKAGE = 'fastqq', chisq_vals, N_hard)
}

